var sites = {
    sitename:[
        {
            name:'www.amazon.com',
            docname:{
                name:'Kindle License Agreement and Terms of Use',
                url:{
                    name:'http://www.amazon.com/gp/help/customer/display.html/?&nodeId=200506200',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.amazon.com',
            docname:{
                name:'Privacy Notice',
                url:{
                    name:'http://www.amazon.com/gp/help/customer/display.html/ref=hp_551434_privacy?nodeId=468496',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.apple.com',
            docname:{
                name:'Customer Privacy Policy',
                url:{
                    name:'http://www.apple.com/privacy/',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.apple.com',
            docname:{
                name:'MobileMe Terms of Service',
                url:{
                    name:'http://www.apple.com/legal/mobileme/en/terms.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.apple.com',
            docname:{
                name:'iTunes Terms Of Service',
                url:{
                    name:'http://www.apple.com/legal/itunes/us/terms.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.blogger.com',
            docname:{
                name:'Blogger Terms Of Service',
                url:{
                    name:'http://www.blogger.com/terms.g',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'twitter.com',
            docname:{
                name:'Terms of Service',
                url:{
                    name:'http://twitter.com/tos',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'wordpress.com',
            docname:{
                name:'WordPress.com Terms Of Service',
                url:{
                    name:'http://en.wordpress.com/tos/',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.comcast.net',
            docname:{
                name:'Acceptable Use Policy',
                url:{
                    name:'http://www.comcast.com/Corporate/Customers/Policies/HighSpeedInternetAUP.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.comcast.net',
            docname:{
                name:'Network Management Policy',
                url:{
                    name:'http://www.comcast.net/terms/network/',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.comcast.net',
            docname:{
                name:'Subscriber Agreement',
                url:{
                    name:'http://www.comcast.com/Corporate/Customers/Policies/SubscriberAgreement.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.craigslist.org',
            docname:{
                name:'Terms Of Use',
                url:{
                    name:'http://www.craigslist.org/about/terms.of.use',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.data.gov',
            docname:{
                name:'Data Policy',
                url:{
                    name:'http://www.data.gov/datapolicy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.data.gov',
            docname:{
                name:'Privacy Policy',
                url:{
                    name:'http://www.data.gov/privacypolicy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.earthlink.net',
            docname:{
                name:'Internet Service Agreement',
                url:{
                    name:'http://www.earthlink.net/about/policies/isa.faces',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'pages.ebay.com',
            docname:{
                name:'User Agreement',
                url:{
                    name:'http://pages.ebay.com/help/policies/user-agreement.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.eff.org',
            docname:{
                name:'Privacy Policy',
                url:{
                    name:'http://www.eff.org/policy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.facebook.com',
            docname:{
                name:'Privacy Policy',
                url:{
                    name:'http://www.facebook.com/full_data_use_policy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.facebook.com',
            docname:{
                name:'Terms of Use',
                url:{
                    name:'http://www.facebook.com/terms.php',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'flickr.com',
            docname:{
                name:'Community Guidelines',
                url:{
                    name:'http://www.flickr.com/guidelines.gne',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.flickr.com',
            docname:{
                name:'Additional Terms of Service',
                url:{
                    name:'http://www.flickr.com/atos/pro/',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Civil Subpoena Policy',
                url:{
                    name:'http://www.godaddy.com/gdshop/legal_agreements/show_doc.asp?plvid=1&pageid=civil_subpoena',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Criminal Subpoena Policy',
                url:{
                    name:'http://www.godaddy.com/gdshop/legal_agreements/show_doc.asp?plvid=1&pageid=crim_subpoena',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Domain Name Proxy Agreement',
                url:{
                    name:'http://www.godaddy.com/gdshop/legal_agreements/show_doc.asp?plvid=1&pageid=domain_nameproxy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Domain Name Registration Agreement',
                url:{
                    name:'http://www.godaddy.com/gdshop/legal_agreements/show_doc.asp?se=%2B&pageid=REG_SA',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Privacy Policy',
                url:{
                    name:'http://www.godaddy.com/gdshop/legal_agreements/show_doc.asp?plvid=1&pageid=privacy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Trademark and Copyright Infringement Policy',
                url:{
                    name:'http://www.godaddy.com/gdshop/legal_agreements/show_doc.asp?plvid=1&pageid=tradmark_copy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Uniform Domain Name Dispute Resolution Policy',
                url:{
                    name:'http://www.godaddy.com/gdshop/legal_agreements/show_doc.asp?plvid=1&pageid=uniform_domain',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.godaddy.com',
            docname:{
                name:'Universal Terms Of Service',
                url:{
                    name:'https://www.godaddy.com/agreements/showdoc.aspx?pageid=UTOS',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'mail.google.com',
            docname:{
                name:'GMail Legal Notices',
                url:{
                    name:'http://mail.google.com/mail/help/intl/en/legal_notices.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'mail.google.com',
            docname:{
                name:'GMail Privacy Policy',
                url:{
                    name:'http://mail.google.com/mail/help/intl/en/privacy.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'mail.google.com',
            docname:{
                name:'GMail Program Policies',
                url:{
                    name:'http://mail.google.com/mail/help/intl/en/program_policies.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.google.com',
            docname:{
                name:'Privacy Policy for Google Ads',
                url:{
                    name:'http://www.google.com/intl/en/privacy_cookies.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'google.com',
            docname:{
                name:'Terms of Service',
                url:{
                    name:'http://www.google.com/accounts/TOS',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'apple.com',
            docname:{
                name:'iTunes Terms of Service',
                url:{
                    name:'http://www.apple.com/legal/itunes/us/terms.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.netflix.com',
            docname:{
                name:'Terms of Use',
                url:{
                    name:'http://www.netflix.com/TermsOfUse',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.sprintpcs.com',
            docname:{
                name:'PCS Terms & Conditions',
                url:{
                    name:'http://www.sprintpcs.com/common/popups/popLegalTermsPrivacy.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.sprintpcs.com',
            docname:{
                name:'PCS Terms & Conditions',
                url:{
                    name:'http://www.sprintpcs.com/common/popups/popLegalTermsPrivacy.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.t-mobile.com',
            docname:{
                name:'Terms and Conditions',
                url:{
                    name:'http://www.t-mobile.com/Templates/Popup.aspx?PAsset=Ftr_Ftr_TermsAndConditions&print=true',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'help.twcable.com',
            docname:{
                name:'Residential Services Subscriber Agreement',
                url:{
                    name:'http://help.twcable.com/html/twc_sub_agreement.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.whitehouse.gov',
            docname:{
                name:'Privacy Policy',
                url:{
                    name:'http://www.whitehouse.gov/privacy/',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.wireless.att.com',
            docname:{
                name:'Wireless Plan Terms',
                url:{
                    name:'http://www.wireless.att.com/cell-phone-service/legal/plan-terms.jsp'
                }
            }
        },
        {
            name:'www.worldofwarcraft.com',
            docname:{
                name:'World Of Warcraft Terms Of Use Agreement',
                url:{
                    name:'http://us.blizzard.com/en-us/company/legal/wow_tou.html',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'yahoo.com',
            docname:{
                name:'Terms of Service',
                url:{
                    name:'http://info.yahoo.com/legal/us/yahoo/utos/'
                }
            }
        },
        {
            name:'www.youtube.com',
            docname:{
                name:'Community Guidelines',
                url:{
                    name:'http://www.youtube.com/t/community_guidelines',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        },
        {
            name:'www.youtube.com',
            docname:{
                name:'Privacy Notice',
                url:{
                    name:'http://www.youtube.com/t/privacy',
                    norecurse:{
                        name:'arbitrary'
                    }
                }
            }
        }
    ]
};